### ISSUE TITLE
A few problem about next_geq() function

### ISSUE THREAD

**Issue by lxy-9602** [jermp/dint#1]
Hello, I do appreciate your clear and well-organized code. But I have a little question. On line 184 of the next_geq.hpp, after calling the next() function, do we need to check whether it has_next() and then perform the CHUNK_MIN operation?  I tested the orignal code with example. If we operate ss.next_geq(x+1), where x is the maximum docID of sequence ss, it will return 0 instead of constants::not_found.

Sorry if I misunderstanding the code.

Sorry I mean in "s_indexes" project...

**Comment by jermp** [comment]
Sorry, I'm closing this for the moment because it is not pertinent with this project.
Could you move this issue here https://github.com/jermp/s_indexes ?
Thanks.
