### ISSUE TITLE
why we execute "make" error?

### ISSUE THREAD

**Issue by MMMolly** [jermp/dint#3]
error: the value of ‘last_end’ is not usable in a constant expressio
error: parse error in template argument list
error: ‘end’ is not a member template function
                     while (window.end < last_end)
error: ‘end’ is not a member template function

**Comment by jermp** [comment]
Hi,
I do not have this error on my end.
What compiler and version are you using?

**Comment by MMMolly** [comment]
thanks for your reply!
my gcc version is 5.4.0
cmake version is 3.14.4
and all details about version and error are in the attachment！


















在 2021-04-21 16:31:36，"Giulio Ermanno Pibiri" ***@***.***> 写道：

Hi,
I do not have this error on my end.
What compiler and version are you using?

**Comment by jermp** [comment]
Can you try to update gcc to a more recent version?
Current version is 9.3...so...
